-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity simple_threshold is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    top_bid_TDATA : IN STD_LOGIC_VECTOR (95 downto 0);
    top_bid_TVALID : IN STD_LOGIC;
    top_bid_TREADY : OUT STD_LOGIC;
    top_ask_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    top_ask_TVALID : IN STD_LOGIC;
    top_ask_TREADY : OUT STD_LOGIC;
    incoming_time_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    incoming_time_TVALID : IN STD_LOGIC;
    incoming_time_TREADY : OUT STD_LOGIC;
    incoming_meta_TDATA : IN STD_LOGIC_VECTOR (95 downto 0);
    incoming_meta_TVALID : IN STD_LOGIC;
    incoming_meta_TREADY : OUT STD_LOGIC;
    outgoing_order_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    outgoing_order_TVALID : OUT STD_LOGIC;
    outgoing_order_TREADY : IN STD_LOGIC;
    outgoing_time_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    outgoing_time_TVALID : OUT STD_LOGIC;
    outgoing_time_TREADY : IN STD_LOGIC;
    outgoing_meta_TDATA : OUT STD_LOGIC_VECTOR (95 downto 0);
    outgoing_meta_TVALID : OUT STD_LOGIC;
    outgoing_meta_TREADY : IN STD_LOGIC );
end;


architecture behav of simple_threshold is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "simple_threshold_simple_threshold,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=7.256500,HLS_SYN_LAT=7,HLS_SYN_TPT=5,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=182,HLS_SYN_LUT=234,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv64_7B020100 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000001111011000000100000000100000000";
    constant ap_const_lv64_10000007B020100 : STD_LOGIC_VECTOR (63 downto 0) := "0000000100000000000000000000000001111011000000100000000100000000";
    constant ap_const_lv16_1B66 : STD_LOGIC_VECTOR (15 downto 0) := "0001101101100110";

    signal ap_rst_n_inv : STD_LOGIC;
    signal top_bid_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4_grp1 : BOOLEAN;
    signal tmp_reg_185 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_189 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_193 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_197 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_201 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_205 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_nbwritereq_fu_108_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal top_ask_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_grp2 : BOOLEAN;
    signal tmp_6_reg_209 : STD_LOGIC_VECTOR (0 downto 0);
    signal incoming_time_TDATA_blk_n : STD_LOGIC;
    signal incoming_meta_TDATA_blk_n : STD_LOGIC;
    signal outgoing_order_TDATA_blk_n : STD_LOGIC;
    signal icmp_ln60_fu_169_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_213 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_fu_179_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_grp5 : BOOLEAN;
    signal tmp_reg_185_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_227 : STD_LOGIC_VECTOR (0 downto 0);
    signal outgoing_time_TDATA_blk_n : STD_LOGIC;
    signal ap_predicate_op48_read_state6 : BOOLEAN;
    signal ap_predicate_op50_read_state6 : BOOLEAN;
    signal ap_predicate_op51_read_state6 : BOOLEAN;
    signal ap_predicate_op52_write_state6 : BOOLEAN;
    signal ap_predicate_op53_write_state6 : BOOLEAN;
    signal ap_predicate_op54_write_state6 : BOOLEAN;
    signal ap_predicate_op57_write_state6 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter1_grp2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp2 : BOOLEAN;
    signal ap_predicate_pred100_state7 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_grp8 : BOOLEAN;
    signal ap_predicate_op58_write_state7 : BOOLEAN;
    signal ap_predicate_op59_write_state7 : BOOLEAN;
    signal ap_predicate_op61_write_state7 : BOOLEAN;
    signal ap_predicate_op62_write_state7 : BOOLEAN;
    signal ap_predicate_op63_write_state7 : BOOLEAN;
    signal ap_block_state7_pp0_stage1_iter1_grp5 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp5 : BOOLEAN;
    signal ap_predicate_pred128_state8 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone_grp8_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage2_subdone_grp8 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal outgoing_meta_TDATA_blk_n : STD_LOGIC;
    signal tmp_nbreadreq_fu_60_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_nbreadreq_fu_68_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_189_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_nbreadreq_fu_76_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_193_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_nbreadreq_fu_84_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_197_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op65_write_state8 : BOOLEAN;
    signal ap_predicate_op66_write_state8 : BOOLEAN;
    signal ap_block_state8_pp0_stage2_iter1_grp8 : BOOLEAN;
    signal ap_block_pp0_stage2_11001_grp8 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal ap_predicate_op43_read_state5 : BOOLEAN;
    signal ap_predicate_op47_write_state5 : BOOLEAN;
    signal ap_block_state5_pp0_stage4_iter0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage4_11001_grp1 : BOOLEAN;
    signal incoming_time_read_reg_217 : STD_LOGIC_VECTOR (63 downto 0);
    signal incoming_meta_read_reg_222 : STD_LOGIC_VECTOR (95 downto 0);
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal regslice_both_outgoing_order_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outgoing_time_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outgoing_meta_U_apdone_blk : STD_LOGIC;
    signal ap_block_pp0_stage4_01001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp2 : BOOLEAN;
    signal ap_block_pp0_stage1_01001_grp5 : BOOLEAN;
    signal bid_price_fu_165_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ask_price_fu_175_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_pp0_stage4_11001 : BOOLEAN;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_top_bid_U_apdone_blk : STD_LOGIC;
    signal top_bid_TDATA_int_regslice : STD_LOGIC_VECTOR (95 downto 0);
    signal top_bid_TVALID_int_regslice : STD_LOGIC;
    signal top_bid_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_top_bid_U_ack_in : STD_LOGIC;
    signal regslice_both_top_ask_U_apdone_blk : STD_LOGIC;
    signal top_ask_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal top_ask_TVALID_int_regslice : STD_LOGIC;
    signal top_ask_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_top_ask_U_ack_in : STD_LOGIC;
    signal regslice_both_incoming_time_U_apdone_blk : STD_LOGIC;
    signal incoming_time_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal incoming_time_TVALID_int_regslice : STD_LOGIC;
    signal incoming_time_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_incoming_time_U_ack_in : STD_LOGIC;
    signal regslice_both_incoming_meta_U_apdone_blk : STD_LOGIC;
    signal incoming_meta_TDATA_int_regslice : STD_LOGIC_VECTOR (95 downto 0);
    signal incoming_meta_TVALID_int_regslice : STD_LOGIC;
    signal incoming_meta_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_incoming_meta_U_ack_in : STD_LOGIC;
    signal outgoing_order_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal outgoing_order_TVALID_int_regslice : STD_LOGIC;
    signal outgoing_order_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_outgoing_order_U_vld_out : STD_LOGIC;
    signal outgoing_time_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal outgoing_time_TVALID_int_regslice : STD_LOGIC;
    signal outgoing_time_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_outgoing_time_U_vld_out : STD_LOGIC;
    signal outgoing_meta_TDATA_int_regslice : STD_LOGIC_VECTOR (95 downto 0);
    signal outgoing_meta_TVALID_int_regslice : STD_LOGIC;
    signal outgoing_meta_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_outgoing_meta_U_vld_out : STD_LOGIC;
    signal ap_condition_519 : BOOLEAN;
    signal ap_condition_523 : BOOLEAN;
    signal ap_condition_526 : BOOLEAN;
    signal ap_condition_530 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component simple_threshold_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_top_bid_U : component simple_threshold_regslice_both
    generic map (
        DataWidth => 96)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => top_bid_TDATA,
        vld_in => top_bid_TVALID,
        ack_in => regslice_both_top_bid_U_ack_in,
        data_out => top_bid_TDATA_int_regslice,
        vld_out => top_bid_TVALID_int_regslice,
        ack_out => top_bid_TREADY_int_regslice,
        apdone_blk => regslice_both_top_bid_U_apdone_blk);

    regslice_both_top_ask_U : component simple_threshold_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => top_ask_TDATA,
        vld_in => top_ask_TVALID,
        ack_in => regslice_both_top_ask_U_ack_in,
        data_out => top_ask_TDATA_int_regslice,
        vld_out => top_ask_TVALID_int_regslice,
        ack_out => top_ask_TREADY_int_regslice,
        apdone_blk => regslice_both_top_ask_U_apdone_blk);

    regslice_both_incoming_time_U : component simple_threshold_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => incoming_time_TDATA,
        vld_in => incoming_time_TVALID,
        ack_in => regslice_both_incoming_time_U_ack_in,
        data_out => incoming_time_TDATA_int_regslice,
        vld_out => incoming_time_TVALID_int_regslice,
        ack_out => incoming_time_TREADY_int_regslice,
        apdone_blk => regslice_both_incoming_time_U_apdone_blk);

    regslice_both_incoming_meta_U : component simple_threshold_regslice_both
    generic map (
        DataWidth => 96)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => incoming_meta_TDATA,
        vld_in => incoming_meta_TVALID,
        ack_in => regslice_both_incoming_meta_U_ack_in,
        data_out => incoming_meta_TDATA_int_regslice,
        vld_out => incoming_meta_TVALID_int_regslice,
        ack_out => incoming_meta_TREADY_int_regslice,
        apdone_blk => regslice_both_incoming_meta_U_apdone_blk);

    regslice_both_outgoing_order_U : component simple_threshold_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => outgoing_order_TDATA_int_regslice,
        vld_in => outgoing_order_TVALID_int_regslice,
        ack_in => outgoing_order_TREADY_int_regslice,
        data_out => outgoing_order_TDATA,
        vld_out => regslice_both_outgoing_order_U_vld_out,
        ack_out => outgoing_order_TREADY,
        apdone_blk => regslice_both_outgoing_order_U_apdone_blk);

    regslice_both_outgoing_time_U : component simple_threshold_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => outgoing_time_TDATA_int_regslice,
        vld_in => outgoing_time_TVALID_int_regslice,
        ack_in => outgoing_time_TREADY_int_regslice,
        data_out => outgoing_time_TDATA,
        vld_out => regslice_both_outgoing_time_U_vld_out,
        ack_out => outgoing_time_TREADY,
        apdone_blk => regslice_both_outgoing_time_U_apdone_blk);

    regslice_both_outgoing_meta_U : component simple_threshold_regslice_both
    generic map (
        DataWidth => 96)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => outgoing_meta_TDATA_int_regslice,
        vld_in => outgoing_meta_TVALID_int_regslice,
        ack_in => outgoing_meta_TREADY_int_regslice,
        data_out => outgoing_meta_TDATA,
        vld_out => regslice_both_outgoing_meta_U_vld_out,
        ack_out => outgoing_meta_TREADY,
        apdone_blk => regslice_both_outgoing_meta_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage2_subdone_grp8_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_block_pp0_stage2_subdone_grp8_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then 
                        ap_block_pp0_stage2_subdone_grp8_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp8)) then 
                        ap_block_pp0_stage2_subdone_grp8_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage4_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    ap_predicate_pred100_state7 <= ((icmp_ln60_reg_213 = ap_const_lv1_1) and (tmp_6_reg_209 = ap_const_lv1_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (tmp_reg_185 = ap_const_lv1_1));
                icmp_ln65_reg_227 <= icmp_ln65_fu_179_p2;
                incoming_meta_read_reg_222 <= incoming_meta_TDATA_int_regslice;
                incoming_time_read_reg_217 <= incoming_time_TDATA_int_regslice;
                tmp_reg_185 <= tmp_nbreadreq_fu_60_p3;
                tmp_reg_185_pp0_iter1_reg <= tmp_reg_185;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                    ap_predicate_pred128_state8 <= ((tmp_6_reg_209 = ap_const_lv1_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (icmp_ln65_reg_227 = ap_const_lv1_1) and (tmp_reg_185_pp0_iter1_reg = ap_const_lv1_1));
                tmp_1_reg_189 <= tmp_1_nbreadreq_fu_68_p3;
                tmp_1_reg_189_pp0_iter1_reg <= tmp_1_reg_189;
                tmp_2_reg_193 <= tmp_2_nbreadreq_fu_76_p3;
                tmp_2_reg_193_pp0_iter1_reg <= tmp_2_reg_193;
                tmp_3_reg_197 <= tmp_3_nbreadreq_fu_84_p3;
                tmp_3_reg_197_pp0_iter1_reg <= tmp_3_reg_197;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                icmp_ln60_reg_213 <= icmp_ln60_fu_169_p2;
                tmp_6_reg_209 <= (0=>outgoing_meta_TREADY_int_regslice, others=>'-');
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp8) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp8_done_reg) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                tmp_4_reg_201 <= (0=>outgoing_order_TREADY_int_regslice, others=>'-');
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                tmp_5_reg_205 <= (0=>outgoing_time_TREADY_int_regslice, others=>'-');
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage2_subdone, ap_block_pp0_stage4_subdone, ap_block_pp0_stage0_subdone, ap_block_pp0_stage1_subdone, ap_reset_idle_pp0, ap_block_pp0_stage3_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_reset_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_reset_idle_pp0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);

    ap_block_pp0_stage0_01001_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state6_pp0_stage0_iter1_grp2)
    begin
                ap_block_pp0_stage0_01001_grp2 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter1_grp2));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state6_pp0_stage0_iter1_grp2)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter1_grp2));
    end process;


    ap_block_pp0_stage0_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state6_pp0_stage0_iter1_grp2)
    begin
                ap_block_pp0_stage0_11001_grp2 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter1_grp2));
    end process;

        ap_block_pp0_stage0_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state6_pp0_stage0_iter1_grp2)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter1_grp2));
    end process;


    ap_block_pp0_stage1_01001_grp5_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state7_pp0_stage1_iter1_grp5)
    begin
                ap_block_pp0_stage1_01001_grp5 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage1_iter1_grp5));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state7_pp0_stage1_iter1_grp5)
    begin
                ap_block_pp0_stage1_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage1_iter1_grp5));
    end process;


    ap_block_pp0_stage1_11001_grp5_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state7_pp0_stage1_iter1_grp5)
    begin
                ap_block_pp0_stage1_11001_grp5 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage1_iter1_grp5));
    end process;

        ap_block_pp0_stage1_grp5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state7_pp0_stage1_iter1_grp5)
    begin
                ap_block_pp0_stage1_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage1_iter1_grp5));
    end process;


    ap_block_pp0_stage2_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_pp0_stage2_subdone_grp8_done_reg, ap_block_state8_pp0_stage2_iter1_grp8, regslice_both_outgoing_order_U_apdone_blk, regslice_both_outgoing_time_U_apdone_blk, regslice_both_outgoing_meta_U_apdone_blk)
    begin
                ap_block_pp0_stage2_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((regslice_both_outgoing_meta_U_apdone_blk = ap_const_logic_1) or (regslice_both_outgoing_time_U_apdone_blk = ap_const_logic_1) or (regslice_both_outgoing_order_U_apdone_blk = ap_const_logic_1) or ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp8_done_reg) and (ap_const_boolean_1 = ap_block_state8_pp0_stage2_iter1_grp8))));
    end process;


    ap_block_pp0_stage2_11001_grp8_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_pp0_stage2_subdone_grp8_done_reg, ap_block_state8_pp0_stage2_iter1_grp8)
    begin
                ap_block_pp0_stage2_11001_grp8 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp8_done_reg) and (ap_const_boolean_1 = ap_block_state8_pp0_stage2_iter1_grp8));
    end process;

        ap_block_pp0_stage2_grp8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_pp0_stage2_subdone_grp8_done_reg, ap_block_state8_pp0_stage2_iter1_grp8, regslice_both_outgoing_order_U_apdone_blk, regslice_both_outgoing_time_U_apdone_blk, regslice_both_outgoing_meta_U_apdone_blk)
    begin
                ap_block_pp0_stage2_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((regslice_both_outgoing_meta_U_apdone_blk = ap_const_logic_1) or (regslice_both_outgoing_time_U_apdone_blk = ap_const_logic_1) or (regslice_both_outgoing_order_U_apdone_blk = ap_const_logic_1) or ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp8_done_reg) and (ap_const_boolean_1 = ap_block_state8_pp0_stage2_iter1_grp8))));
    end process;


    ap_block_pp0_stage2_subdone_grp8_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_pp0_stage2_subdone_grp8_done_reg, ap_block_state8_pp0_stage2_iter1_grp8)
    begin
                ap_block_pp0_stage2_subdone_grp8 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp8_done_reg) and (ap_const_boolean_1 = ap_block_state8_pp0_stage2_iter1_grp8));
    end process;

        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage4_01001_grp1_assign_proc : process(ap_block_state5_pp0_stage4_iter0_grp1)
    begin
                ap_block_pp0_stage4_01001_grp1 <= ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0_grp1));
    end process;


    ap_block_pp0_stage4_11001_assign_proc : process(ap_block_state5_pp0_stage4_iter0_grp1)
    begin
                ap_block_pp0_stage4_11001 <= ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0_grp1));
    end process;


    ap_block_pp0_stage4_11001_grp1_assign_proc : process(ap_block_state5_pp0_stage4_iter0_grp1)
    begin
                ap_block_pp0_stage4_11001_grp1 <= ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0_grp1));
    end process;

        ap_block_pp0_stage4_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage4_subdone_assign_proc : process(ap_block_state5_pp0_stage4_iter0_grp1)
    begin
                ap_block_pp0_stage4_subdone <= ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage4_iter0_grp1));
    end process;


    ap_block_state5_pp0_stage4_iter0_grp1_assign_proc : process(ap_predicate_op43_read_state5, ap_predicate_op47_write_state5, top_bid_TVALID_int_regslice, outgoing_order_TREADY_int_regslice)
    begin
                ap_block_state5_pp0_stage4_iter0_grp1 <= (((outgoing_order_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op47_write_state5 = ap_const_boolean_1)) or ((top_bid_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op43_read_state5 = ap_const_boolean_1)));
    end process;


    ap_block_state6_pp0_stage0_iter1_grp2_assign_proc : process(ap_predicate_op48_read_state6, ap_predicate_op50_read_state6, ap_predicate_op51_read_state6, ap_predicate_op52_write_state6, ap_predicate_op53_write_state6, ap_predicate_op54_write_state6, ap_predicate_op57_write_state6, top_ask_TVALID_int_regslice, incoming_time_TVALID_int_regslice, incoming_meta_TVALID_int_regslice, outgoing_order_TREADY_int_regslice, outgoing_time_TREADY_int_regslice, outgoing_meta_TREADY_int_regslice)
    begin
                ap_block_state6_pp0_stage0_iter1_grp2 <= (((outgoing_meta_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op53_write_state6 = ap_const_boolean_1)) or ((outgoing_time_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op54_write_state6 = ap_const_boolean_1)) or ((outgoing_order_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op57_write_state6 = ap_const_boolean_1)) or ((outgoing_order_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op52_write_state6 = ap_const_boolean_1)) or ((incoming_meta_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op51_read_state6 = ap_const_boolean_1)) or ((incoming_time_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op50_read_state6 = ap_const_boolean_1)) or ((top_ask_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op48_read_state6 = ap_const_boolean_1)));
    end process;


    ap_block_state7_pp0_stage1_iter1_grp5_assign_proc : process(ap_predicate_op58_write_state7, ap_predicate_op59_write_state7, ap_predicate_op61_write_state7, ap_predicate_op62_write_state7, ap_predicate_op63_write_state7, outgoing_order_TREADY_int_regslice, outgoing_time_TREADY_int_regslice, outgoing_meta_TREADY_int_regslice)
    begin
                ap_block_state7_pp0_stage1_iter1_grp5 <= (((outgoing_meta_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op62_write_state7 = ap_const_boolean_1)) or ((outgoing_meta_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op58_write_state7 = ap_const_boolean_1)) or ((outgoing_time_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op63_write_state7 = ap_const_boolean_1)) or ((outgoing_time_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op59_write_state7 = ap_const_boolean_1)) or ((outgoing_order_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op61_write_state7 = ap_const_boolean_1)));
    end process;


    ap_block_state8_pp0_stage2_iter1_grp8_assign_proc : process(ap_predicate_op65_write_state8, ap_predicate_op66_write_state8, outgoing_time_TREADY_int_regslice, outgoing_meta_TREADY_int_regslice)
    begin
                ap_block_state8_pp0_stage2_iter1_grp8 <= (((outgoing_meta_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op65_write_state8 = ap_const_boolean_1)) or ((outgoing_time_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state8 = ap_const_boolean_1)));
    end process;


    ap_condition_519_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_predicate_op53_write_state6, ap_block_pp0_stage0_01001_grp2)
    begin
                ap_condition_519 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op53_write_state6 = ap_const_boolean_1));
    end process;


    ap_condition_523_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_predicate_op62_write_state7, ap_block_pp0_stage1_01001_grp5)
    begin
                ap_condition_523 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_01001_grp5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_predicate_op62_write_state7 = ap_const_boolean_1));
    end process;


    ap_condition_526_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_predicate_op54_write_state6, ap_block_pp0_stage0_01001_grp2)
    begin
                ap_condition_526 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op54_write_state6 = ap_const_boolean_1));
    end process;


    ap_condition_530_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_predicate_op63_write_state7, ap_block_pp0_stage1_01001_grp5)
    begin
                ap_condition_530 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_01001_grp5) and (ap_predicate_op63_write_state7 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op43_read_state5_assign_proc : process(tmp_reg_185, tmp_1_reg_189, tmp_2_reg_193, tmp_3_reg_197, tmp_4_reg_201, tmp_5_reg_205, grp_nbwritereq_fu_108_p3)
    begin
                ap_predicate_op43_read_state5 <= ((grp_nbwritereq_fu_108_p3 = ap_const_lv1_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (tmp_reg_185 = ap_const_lv1_1));
    end process;


    ap_predicate_op47_write_state5_assign_proc : process(tmp_reg_185, tmp_1_reg_189, tmp_2_reg_193, tmp_3_reg_197, tmp_4_reg_201, tmp_5_reg_205, grp_nbwritereq_fu_108_p3, icmp_ln60_fu_169_p2)
    begin
                ap_predicate_op47_write_state5 <= ((icmp_ln60_fu_169_p2 = ap_const_lv1_1) and (grp_nbwritereq_fu_108_p3 = ap_const_lv1_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (tmp_reg_185 = ap_const_lv1_1));
    end process;


    ap_predicate_op48_read_state6_assign_proc : process(tmp_reg_185, tmp_1_reg_189, tmp_2_reg_193, tmp_3_reg_197, tmp_4_reg_201, tmp_5_reg_205, tmp_6_reg_209)
    begin
                ap_predicate_op48_read_state6 <= ((tmp_6_reg_209 = ap_const_lv1_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (tmp_reg_185 = ap_const_lv1_1));
    end process;


    ap_predicate_op50_read_state6_assign_proc : process(tmp_reg_185, tmp_1_reg_189, tmp_2_reg_193, tmp_3_reg_197, tmp_4_reg_201, tmp_5_reg_205, tmp_6_reg_209)
    begin
                ap_predicate_op50_read_state6 <= ((tmp_6_reg_209 = ap_const_lv1_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (tmp_reg_185 = ap_const_lv1_1));
    end process;


    ap_predicate_op51_read_state6_assign_proc : process(tmp_reg_185, tmp_1_reg_189, tmp_2_reg_193, tmp_3_reg_197, tmp_4_reg_201, tmp_5_reg_205, tmp_6_reg_209)
    begin
                ap_predicate_op51_read_state6 <= ((tmp_6_reg_209 = ap_const_lv1_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (tmp_reg_185 = ap_const_lv1_1));
    end process;


    ap_predicate_op52_write_state6_assign_proc : process(tmp_reg_185, tmp_1_reg_189, tmp_2_reg_193, tmp_3_reg_197, tmp_4_reg_201, tmp_5_reg_205, tmp_6_reg_209, icmp_ln60_reg_213)
    begin
                ap_predicate_op52_write_state6 <= ((icmp_ln60_reg_213 = ap_const_lv1_1) and (tmp_6_reg_209 = ap_const_lv1_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (tmp_reg_185 = ap_const_lv1_1));
    end process;


    ap_predicate_op53_write_state6_assign_proc : process(tmp_reg_185, tmp_1_reg_189, tmp_2_reg_193, tmp_3_reg_197, tmp_4_reg_201, tmp_5_reg_205, tmp_6_reg_209, icmp_ln60_reg_213)
    begin
                ap_predicate_op53_write_state6 <= ((icmp_ln60_reg_213 = ap_const_lv1_1) and (tmp_6_reg_209 = ap_const_lv1_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (tmp_reg_185 = ap_const_lv1_1));
    end process;


    ap_predicate_op54_write_state6_assign_proc : process(tmp_reg_185, tmp_1_reg_189, tmp_2_reg_193, tmp_3_reg_197, tmp_4_reg_201, tmp_5_reg_205, tmp_6_reg_209, icmp_ln60_reg_213)
    begin
                ap_predicate_op54_write_state6 <= ((icmp_ln60_reg_213 = ap_const_lv1_1) and (tmp_6_reg_209 = ap_const_lv1_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (tmp_reg_185 = ap_const_lv1_1));
    end process;


    ap_predicate_op57_write_state6_assign_proc : process(tmp_reg_185, tmp_1_reg_189, tmp_2_reg_193, tmp_3_reg_197, tmp_4_reg_201, tmp_5_reg_205, tmp_6_reg_209, icmp_ln65_fu_179_p2)
    begin
                ap_predicate_op57_write_state6 <= ((tmp_6_reg_209 = ap_const_lv1_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (tmp_reg_185 = ap_const_lv1_1) and (icmp_ln65_fu_179_p2 = ap_const_lv1_1));
    end process;


    ap_predicate_op58_write_state7_assign_proc : process(tmp_1_reg_189, tmp_2_reg_193, tmp_3_reg_197, tmp_4_reg_201, tmp_5_reg_205, tmp_6_reg_209, icmp_ln60_reg_213, tmp_reg_185_pp0_iter1_reg)
    begin
                ap_predicate_op58_write_state7 <= ((icmp_ln60_reg_213 = ap_const_lv1_1) and (tmp_6_reg_209 = ap_const_lv1_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (tmp_reg_185_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op59_write_state7_assign_proc : process(tmp_1_reg_189, tmp_2_reg_193, tmp_3_reg_197, tmp_4_reg_201, tmp_5_reg_205, tmp_6_reg_209, icmp_ln60_reg_213, tmp_reg_185_pp0_iter1_reg)
    begin
                ap_predicate_op59_write_state7 <= ((icmp_ln60_reg_213 = ap_const_lv1_1) and (tmp_6_reg_209 = ap_const_lv1_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (tmp_reg_185_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op61_write_state7_assign_proc : process(tmp_1_reg_189, tmp_2_reg_193, tmp_3_reg_197, tmp_4_reg_201, tmp_5_reg_205, tmp_6_reg_209, tmp_reg_185_pp0_iter1_reg, icmp_ln65_reg_227)
    begin
                ap_predicate_op61_write_state7 <= ((tmp_6_reg_209 = ap_const_lv1_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (icmp_ln65_reg_227 = ap_const_lv1_1) and (tmp_reg_185_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op62_write_state7_assign_proc : process(tmp_1_reg_189, tmp_2_reg_193, tmp_3_reg_197, tmp_4_reg_201, tmp_5_reg_205, tmp_6_reg_209, tmp_reg_185_pp0_iter1_reg, icmp_ln65_reg_227)
    begin
                ap_predicate_op62_write_state7 <= ((tmp_6_reg_209 = ap_const_lv1_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (icmp_ln65_reg_227 = ap_const_lv1_1) and (tmp_reg_185_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op63_write_state7_assign_proc : process(tmp_1_reg_189, tmp_2_reg_193, tmp_3_reg_197, tmp_4_reg_201, tmp_5_reg_205, tmp_6_reg_209, tmp_reg_185_pp0_iter1_reg, icmp_ln65_reg_227)
    begin
                ap_predicate_op63_write_state7 <= ((tmp_6_reg_209 = ap_const_lv1_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (icmp_ln65_reg_227 = ap_const_lv1_1) and (tmp_reg_185_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op65_write_state8_assign_proc : process(tmp_4_reg_201, tmp_5_reg_205, tmp_6_reg_209, tmp_reg_185_pp0_iter1_reg, icmp_ln65_reg_227, tmp_1_reg_189_pp0_iter1_reg, tmp_2_reg_193_pp0_iter1_reg, tmp_3_reg_197_pp0_iter1_reg)
    begin
                ap_predicate_op65_write_state8 <= ((tmp_6_reg_209 = ap_const_lv1_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197_pp0_iter1_reg = ap_const_lv1_1) and (tmp_2_reg_193_pp0_iter1_reg = ap_const_lv1_1) and (tmp_1_reg_189_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln65_reg_227 = ap_const_lv1_1) and (tmp_reg_185_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op66_write_state8_assign_proc : process(tmp_4_reg_201, tmp_5_reg_205, tmp_6_reg_209, tmp_reg_185_pp0_iter1_reg, icmp_ln65_reg_227, tmp_1_reg_189_pp0_iter1_reg, tmp_2_reg_193_pp0_iter1_reg, tmp_3_reg_197_pp0_iter1_reg)
    begin
                ap_predicate_op66_write_state8 <= ((tmp_6_reg_209 = ap_const_lv1_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197_pp0_iter1_reg = ap_const_lv1_1) and (tmp_2_reg_193_pp0_iter1_reg = ap_const_lv1_1) and (tmp_1_reg_189_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln65_reg_227 = ap_const_lv1_1) and (tmp_reg_185_pp0_iter1_reg = ap_const_lv1_1));
    end process;

    ap_reset_idle_pp0 <= ap_const_logic_0;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ask_price_fu_175_p1 <= top_ask_TDATA_int_regslice(16 - 1 downto 0);
    bid_price_fu_165_p1 <= top_bid_TDATA_int_regslice(16 - 1 downto 0);
    grp_nbwritereq_fu_108_p3 <= (0=>outgoing_meta_TREADY_int_regslice, others=>'-');
    icmp_ln60_fu_169_p2 <= "1" when (unsigned(bid_price_fu_165_p1) > unsigned(ap_const_lv16_1B66)) else "0";
    icmp_ln65_fu_179_p2 <= "1" when (unsigned(ask_price_fu_175_p1) < unsigned(ap_const_lv16_1B66)) else "0";

    incoming_meta_TDATA_blk_n_assign_proc : process(tmp_reg_185, tmp_1_reg_189, tmp_2_reg_193, tmp_3_reg_197, tmp_4_reg_201, tmp_5_reg_205, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_grp2, tmp_6_reg_209, incoming_meta_TVALID_int_regslice)
    begin
        if (((tmp_6_reg_209 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (tmp_reg_185 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            incoming_meta_TDATA_blk_n <= incoming_meta_TVALID_int_regslice;
        else 
            incoming_meta_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    incoming_meta_TREADY <= regslice_both_incoming_meta_U_ack_in;

    incoming_meta_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op51_read_state6, ap_block_pp0_stage0_11001_grp2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op51_read_state6 = ap_const_boolean_1))) then 
            incoming_meta_TREADY_int_regslice <= ap_const_logic_1;
        else 
            incoming_meta_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    incoming_time_TDATA_blk_n_assign_proc : process(tmp_reg_185, tmp_1_reg_189, tmp_2_reg_193, tmp_3_reg_197, tmp_4_reg_201, tmp_5_reg_205, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_grp2, tmp_6_reg_209, incoming_time_TVALID_int_regslice)
    begin
        if (((tmp_6_reg_209 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (tmp_reg_185 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            incoming_time_TDATA_blk_n <= incoming_time_TVALID_int_regslice;
        else 
            incoming_time_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    incoming_time_TREADY <= regslice_both_incoming_time_U_ack_in;

    incoming_time_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op50_read_state6, ap_block_pp0_stage0_11001_grp2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op50_read_state6 = ap_const_boolean_1))) then 
            incoming_time_TREADY_int_regslice <= ap_const_logic_1;
        else 
            incoming_time_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    outgoing_meta_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_grp2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_grp5, ap_predicate_op53_write_state6, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_grp8, ap_predicate_op58_write_state7, ap_predicate_op62_write_state7, ap_predicate_pred128_state8, ap_block_pp0_stage2_subdone_grp8_done_reg, outgoing_meta_TREADY_int_regslice)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op53_write_state6 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp8_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp8) and (ap_predicate_pred128_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_predicate_op62_write_state7 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_predicate_op58_write_state7 = ap_const_boolean_1)))) then 
            outgoing_meta_TDATA_blk_n <= outgoing_meta_TREADY_int_regslice;
        else 
            outgoing_meta_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    outgoing_meta_TDATA_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter1, incoming_meta_read_reg_222, incoming_meta_TDATA_int_regslice, ap_condition_519, ap_condition_523)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then
            if ((ap_const_boolean_1 = ap_condition_523)) then 
                outgoing_meta_TDATA_int_regslice <= incoming_meta_read_reg_222;
            elsif ((ap_const_boolean_1 = ap_condition_519)) then 
                outgoing_meta_TDATA_int_regslice <= incoming_meta_TDATA_int_regslice;
            else 
                outgoing_meta_TDATA_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            outgoing_meta_TDATA_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    outgoing_meta_TVALID <= regslice_both_outgoing_meta_U_vld_out;

    outgoing_meta_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_predicate_op53_write_state6, ap_block_pp0_stage0_11001_grp2, ap_predicate_op62_write_state7, ap_block_pp0_stage1_11001_grp5)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_predicate_op62_write_state7 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op53_write_state6 = ap_const_boolean_1)))) then 
            outgoing_meta_TVALID_int_regslice <= ap_const_logic_1;
        else 
            outgoing_meta_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    outgoing_order_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_grp1, tmp_reg_185, tmp_1_reg_189, tmp_2_reg_193, tmp_3_reg_197, tmp_4_reg_201, tmp_5_reg_205, grp_nbwritereq_fu_108_p3, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_grp2, tmp_6_reg_209, icmp_ln60_fu_169_p2, icmp_ln60_reg_213, icmp_ln65_fu_179_p2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_grp5, tmp_reg_185_pp0_iter1_reg, icmp_ln65_reg_227, outgoing_order_TREADY_int_regslice)
    begin
        if ((((icmp_ln60_reg_213 = ap_const_lv1_1) and (tmp_6_reg_209 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (tmp_reg_185 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln60_fu_169_p2 = ap_const_lv1_1) and (grp_nbwritereq_fu_108_p3 = ap_const_lv1_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (tmp_reg_185 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_grp1) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((tmp_6_reg_209 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 
    = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (tmp_reg_185 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln65_fu_179_p2 = ap_const_lv1_1)) or ((tmp_6_reg_209 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln65_reg_227 = ap_const_lv1_1) and (tmp_reg_185_pp0_iter1_reg = ap_const_lv1_1)))) then 
            outgoing_order_TDATA_blk_n <= outgoing_order_TREADY_int_regslice;
        else 
            outgoing_order_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    outgoing_order_TDATA_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op57_write_state6, ap_predicate_op47_write_state5, ap_block_pp0_stage4_01001_grp1, ap_block_pp0_stage0_01001_grp2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op57_write_state6 = ap_const_boolean_1))) then 
            outgoing_order_TDATA_int_regslice <= ap_const_lv64_10000007B020100;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage4_01001_grp1) and (ap_const_logic_1 = ap_const_logic_1) and (ap_predicate_op47_write_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            outgoing_order_TDATA_int_regslice <= ap_const_lv64_7B020100;
        else 
            outgoing_order_TDATA_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    outgoing_order_TVALID <= regslice_both_outgoing_order_U_vld_out;

    outgoing_order_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op57_write_state6, ap_block_pp0_stage0_11001_grp2, ap_predicate_op47_write_state5, ap_block_pp0_stage4_11001_grp1)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op57_write_state6 = ap_const_boolean_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp1) and (ap_const_logic_1 = ap_const_logic_1) and (ap_predicate_op47_write_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)))) then 
            outgoing_order_TVALID_int_regslice <= ap_const_logic_1;
        else 
            outgoing_order_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    outgoing_time_TDATA_blk_n_assign_proc : process(tmp_reg_185, tmp_1_reg_189, tmp_2_reg_193, tmp_3_reg_197, tmp_4_reg_201, tmp_5_reg_205, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_grp2, tmp_6_reg_209, icmp_ln60_reg_213, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_grp5, tmp_reg_185_pp0_iter1_reg, icmp_ln65_reg_227, ap_predicate_pred100_state7, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_grp8, ap_predicate_pred128_state8, ap_block_pp0_stage2_subdone_grp8_done_reg, outgoing_time_TREADY_int_regslice)
    begin
        if ((((icmp_ln60_reg_213 = ap_const_lv1_1) and (tmp_6_reg_209 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (tmp_reg_185 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((tmp_6_reg_209 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln65_reg_227 = ap_const_lv1_1) and (tmp_reg_185_pp0_iter1_reg = ap_const_lv1_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp8_done_reg) and 
    (ap_const_boolean_0 = ap_block_pp0_stage2_grp8) and (ap_predicate_pred128_state8 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_predicate_pred100_state7 = ap_const_boolean_1)))) then 
            outgoing_time_TDATA_blk_n <= outgoing_time_TREADY_int_regslice;
        else 
            outgoing_time_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    outgoing_time_TDATA_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter1, incoming_time_read_reg_217, incoming_time_TDATA_int_regslice, ap_condition_526, ap_condition_530)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then
            if ((ap_const_boolean_1 = ap_condition_530)) then 
                outgoing_time_TDATA_int_regslice <= incoming_time_read_reg_217;
            elsif ((ap_const_boolean_1 = ap_condition_526)) then 
                outgoing_time_TDATA_int_regslice <= incoming_time_TDATA_int_regslice;
            else 
                outgoing_time_TDATA_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            outgoing_time_TDATA_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    outgoing_time_TVALID <= regslice_both_outgoing_time_U_vld_out;

    outgoing_time_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_predicate_op54_write_state6, ap_block_pp0_stage0_11001_grp2, ap_predicate_op63_write_state7, ap_block_pp0_stage1_11001_grp5)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp5) and (ap_predicate_op63_write_state7 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op54_write_state6 = ap_const_boolean_1)))) then 
            outgoing_time_TVALID_int_regslice <= ap_const_logic_1;
        else 
            outgoing_time_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_nbreadreq_fu_68_p3 <= (0=>(top_ask_TVALID_int_regslice), others=>'-');
    tmp_2_nbreadreq_fu_76_p3 <= (0=>(incoming_time_TVALID_int_regslice), others=>'-');
    tmp_3_nbreadreq_fu_84_p3 <= (0=>(incoming_meta_TVALID_int_regslice), others=>'-');
    tmp_nbreadreq_fu_60_p3 <= (0=>(top_bid_TVALID_int_regslice), others=>'-');

    top_ask_TDATA_blk_n_assign_proc : process(tmp_reg_185, tmp_1_reg_189, tmp_2_reg_193, tmp_3_reg_197, tmp_4_reg_201, tmp_5_reg_205, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_grp2, tmp_6_reg_209, top_ask_TVALID_int_regslice)
    begin
        if (((tmp_6_reg_209 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (tmp_reg_185 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            top_ask_TDATA_blk_n <= top_ask_TVALID_int_regslice;
        else 
            top_ask_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    top_ask_TREADY <= regslice_both_top_ask_U_ack_in;

    top_ask_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op48_read_state6, ap_block_pp0_stage0_11001_grp2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op48_read_state6 = ap_const_boolean_1))) then 
            top_ask_TREADY_int_regslice <= ap_const_logic_1;
        else 
            top_ask_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    top_bid_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_grp1, tmp_reg_185, tmp_1_reg_189, tmp_2_reg_193, tmp_3_reg_197, tmp_4_reg_201, tmp_5_reg_205, grp_nbwritereq_fu_108_p3, top_bid_TVALID_int_regslice)
    begin
        if (((grp_nbwritereq_fu_108_p3 = ap_const_lv1_1) and (tmp_5_reg_205 = ap_const_lv1_1) and (tmp_4_reg_201 = ap_const_lv1_1) and (tmp_3_reg_197 = ap_const_lv1_1) and (tmp_2_reg_193 = ap_const_lv1_1) and (tmp_1_reg_189 = ap_const_lv1_1) and (tmp_reg_185 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_grp1) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            top_bid_TDATA_blk_n <= top_bid_TVALID_int_regslice;
        else 
            top_bid_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    top_bid_TREADY <= regslice_both_top_bid_U_ack_in;

    top_bid_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage4, ap_predicate_op43_read_state5, ap_block_pp0_stage4_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp1) and (ap_const_logic_1 = ap_const_logic_1) and (ap_predicate_op43_read_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            top_bid_TREADY_int_regslice <= ap_const_logic_1;
        else 
            top_bid_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

end behav;
