// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="simple_threshold_simple_threshold,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=7.256500,HLS_SYN_LAT=7,HLS_SYN_TPT=5,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=182,HLS_SYN_LUT=234,HLS_VERSION=2024_2}" *)

module simple_threshold (
        ap_clk,
        ap_rst_n,
        top_bid_TDATA,
        top_bid_TVALID,
        top_bid_TREADY,
        top_ask_TDATA,
        top_ask_TVALID,
        top_ask_TREADY,
        incoming_time_TDATA,
        incoming_time_TVALID,
        incoming_time_TREADY,
        incoming_meta_TDATA,
        incoming_meta_TVALID,
        incoming_meta_TREADY,
        outgoing_order_TDATA,
        outgoing_order_TVALID,
        outgoing_order_TREADY,
        outgoing_time_TDATA,
        outgoing_time_TVALID,
        outgoing_time_TREADY,
        outgoing_meta_TDATA,
        outgoing_meta_TVALID,
        outgoing_meta_TREADY
);

parameter    ap_ST_fsm_pp0_stage0 = 5'd1;
parameter    ap_ST_fsm_pp0_stage1 = 5'd2;
parameter    ap_ST_fsm_pp0_stage2 = 5'd4;
parameter    ap_ST_fsm_pp0_stage3 = 5'd8;
parameter    ap_ST_fsm_pp0_stage4 = 5'd16;

input   ap_clk;
input   ap_rst_n;
input  [95:0] top_bid_TDATA;
input   top_bid_TVALID;
output   top_bid_TREADY;
input  [63:0] top_ask_TDATA;
input   top_ask_TVALID;
output   top_ask_TREADY;
input  [63:0] incoming_time_TDATA;
input   incoming_time_TVALID;
output   incoming_time_TREADY;
input  [95:0] incoming_meta_TDATA;
input   incoming_meta_TVALID;
output   incoming_meta_TREADY;
output  [63:0] outgoing_order_TDATA;
output   outgoing_order_TVALID;
input   outgoing_order_TREADY;
output  [63:0] outgoing_time_TDATA;
output   outgoing_time_TVALID;
input   outgoing_time_TREADY;
output  [95:0] outgoing_meta_TDATA;
output   outgoing_meta_TVALID;
input   outgoing_meta_TREADY;

 reg    ap_rst_n_inv;
reg    top_bid_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_grp1;
reg   [0:0] tmp_reg_185;
reg   [0:0] tmp_1_reg_189;
reg   [0:0] tmp_2_reg_193;
reg   [0:0] tmp_3_reg_197;
reg   [0:0] tmp_4_reg_201;
reg   [0:0] tmp_5_reg_205;
wire   [0:0] grp_nbwritereq_fu_108_p3;
reg    top_ask_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0_grp2;
reg   [0:0] tmp_6_reg_209;
reg    incoming_time_TDATA_blk_n;
reg    incoming_meta_TDATA_blk_n;
reg    outgoing_order_TDATA_blk_n;
wire   [0:0] icmp_ln60_fu_169_p2;
reg   [0:0] icmp_ln60_reg_213;
wire   [0:0] icmp_ln65_fu_179_p2;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp5;
reg   [0:0] tmp_reg_185_pp0_iter1_reg;
reg   [0:0] icmp_ln65_reg_227;
reg    outgoing_time_TDATA_blk_n;
reg    ap_predicate_op48_read_state6;
reg    ap_predicate_op50_read_state6;
reg    ap_predicate_op51_read_state6;
reg    ap_predicate_op52_write_state6;
reg    ap_predicate_op53_write_state6;
reg    ap_predicate_op54_write_state6;
reg    ap_predicate_op57_write_state6;
reg    ap_block_state6_pp0_stage0_iter1_grp2;
reg    ap_block_pp0_stage0_11001_grp2;
reg    ap_predicate_pred100_state7;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_grp8;
reg    ap_predicate_op58_write_state7;
reg    ap_predicate_op59_write_state7;
reg    ap_predicate_op61_write_state7;
reg    ap_predicate_op62_write_state7;
reg    ap_predicate_op63_write_state7;
reg    ap_block_state7_pp0_stage1_iter1_grp5;
reg    ap_block_pp0_stage1_11001_grp5;
reg    ap_predicate_pred128_state8;
reg    ap_block_pp0_stage2_subdone_grp8_done_reg;
reg    ap_block_pp0_stage2_subdone_grp8;
reg    ap_block_pp0_stage2_subdone;
reg    outgoing_meta_TDATA_blk_n;
wire   [0:0] tmp_nbreadreq_fu_60_p3;
wire   [0:0] tmp_1_nbreadreq_fu_68_p3;
reg   [0:0] tmp_1_reg_189_pp0_iter1_reg;
wire   [0:0] tmp_2_nbreadreq_fu_76_p3;
reg   [0:0] tmp_2_reg_193_pp0_iter1_reg;
wire   [0:0] tmp_3_nbreadreq_fu_84_p3;
reg   [0:0] tmp_3_reg_197_pp0_iter1_reg;
reg    ap_predicate_op65_write_state8;
reg    ap_predicate_op66_write_state8;
reg    ap_block_state8_pp0_stage2_iter1_grp8;
reg    ap_block_pp0_stage2_11001_grp8;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
reg    ap_predicate_op43_read_state5;
reg    ap_predicate_op47_write_state5;
reg    ap_block_state5_pp0_stage4_iter0_grp1;
reg    ap_block_pp0_stage4_11001_grp1;
reg   [63:0] incoming_time_read_reg_217;
reg   [95:0] incoming_meta_read_reg_222;
reg    ap_block_pp0_stage4_subdone;
wire    regslice_both_outgoing_order_U_apdone_blk;
wire    regslice_both_outgoing_time_U_apdone_blk;
wire    regslice_both_outgoing_meta_U_apdone_blk;
reg    ap_block_pp0_stage4_01001_grp1;
reg    ap_block_pp0_stage0_01001_grp2;
reg    ap_block_pp0_stage1_01001_grp5;
wire   [15:0] bid_price_fu_165_p1;
wire   [15:0] ask_price_fu_175_p1;
reg   [4:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage0_11001;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage1_11001;
wire    ap_reset_idle_pp0;
reg    ap_block_pp0_stage2_11001;
wire    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage4_11001;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_top_bid_U_apdone_blk;
wire   [95:0] top_bid_TDATA_int_regslice;
wire    top_bid_TVALID_int_regslice;
reg    top_bid_TREADY_int_regslice;
wire    regslice_both_top_bid_U_ack_in;
wire    regslice_both_top_ask_U_apdone_blk;
wire   [63:0] top_ask_TDATA_int_regslice;
wire    top_ask_TVALID_int_regslice;
reg    top_ask_TREADY_int_regslice;
wire    regslice_both_top_ask_U_ack_in;
wire    regslice_both_incoming_time_U_apdone_blk;
wire   [63:0] incoming_time_TDATA_int_regslice;
wire    incoming_time_TVALID_int_regslice;
reg    incoming_time_TREADY_int_regslice;
wire    regslice_both_incoming_time_U_ack_in;
wire    regslice_both_incoming_meta_U_apdone_blk;
wire   [95:0] incoming_meta_TDATA_int_regslice;
wire    incoming_meta_TVALID_int_regslice;
reg    incoming_meta_TREADY_int_regslice;
wire    regslice_both_incoming_meta_U_ack_in;
reg   [63:0] outgoing_order_TDATA_int_regslice;
reg    outgoing_order_TVALID_int_regslice;
wire    outgoing_order_TREADY_int_regslice;
wire    regslice_both_outgoing_order_U_vld_out;
reg   [63:0] outgoing_time_TDATA_int_regslice;
reg    outgoing_time_TVALID_int_regslice;
wire    outgoing_time_TREADY_int_regslice;
wire    regslice_both_outgoing_time_U_vld_out;
reg   [95:0] outgoing_meta_TDATA_int_regslice;
reg    outgoing_meta_TVALID_int_regslice;
wire    outgoing_meta_TREADY_int_regslice;
wire    regslice_both_outgoing_meta_U_vld_out;
reg    ap_condition_519;
reg    ap_condition_523;
reg    ap_condition_526;
reg    ap_condition_530;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp8_done_reg = 1'b0;
end

simple_threshold_regslice_both #(
    .DataWidth( 96 ))
regslice_both_top_bid_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(top_bid_TDATA),
    .vld_in(top_bid_TVALID),
    .ack_in(regslice_both_top_bid_U_ack_in),
    .data_out(top_bid_TDATA_int_regslice),
    .vld_out(top_bid_TVALID_int_regslice),
    .ack_out(top_bid_TREADY_int_regslice),
    .apdone_blk(regslice_both_top_bid_U_apdone_blk)
);

simple_threshold_regslice_both #(
    .DataWidth( 64 ))
regslice_both_top_ask_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(top_ask_TDATA),
    .vld_in(top_ask_TVALID),
    .ack_in(regslice_both_top_ask_U_ack_in),
    .data_out(top_ask_TDATA_int_regslice),
    .vld_out(top_ask_TVALID_int_regslice),
    .ack_out(top_ask_TREADY_int_regslice),
    .apdone_blk(regslice_both_top_ask_U_apdone_blk)
);

simple_threshold_regslice_both #(
    .DataWidth( 64 ))
regslice_both_incoming_time_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(incoming_time_TDATA),
    .vld_in(incoming_time_TVALID),
    .ack_in(regslice_both_incoming_time_U_ack_in),
    .data_out(incoming_time_TDATA_int_regslice),
    .vld_out(incoming_time_TVALID_int_regslice),
    .ack_out(incoming_time_TREADY_int_regslice),
    .apdone_blk(regslice_both_incoming_time_U_apdone_blk)
);

simple_threshold_regslice_both #(
    .DataWidth( 96 ))
regslice_both_incoming_meta_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(incoming_meta_TDATA),
    .vld_in(incoming_meta_TVALID),
    .ack_in(regslice_both_incoming_meta_U_ack_in),
    .data_out(incoming_meta_TDATA_int_regslice),
    .vld_out(incoming_meta_TVALID_int_regslice),
    .ack_out(incoming_meta_TREADY_int_regslice),
    .apdone_blk(regslice_both_incoming_meta_U_apdone_blk)
);

simple_threshold_regslice_both #(
    .DataWidth( 64 ))
regslice_both_outgoing_order_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(outgoing_order_TDATA_int_regslice),
    .vld_in(outgoing_order_TVALID_int_regslice),
    .ack_in(outgoing_order_TREADY_int_regslice),
    .data_out(outgoing_order_TDATA),
    .vld_out(regslice_both_outgoing_order_U_vld_out),
    .ack_out(outgoing_order_TREADY),
    .apdone_blk(regslice_both_outgoing_order_U_apdone_blk)
);

simple_threshold_regslice_both #(
    .DataWidth( 64 ))
regslice_both_outgoing_time_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(outgoing_time_TDATA_int_regslice),
    .vld_in(outgoing_time_TVALID_int_regslice),
    .ack_in(outgoing_time_TREADY_int_regslice),
    .data_out(outgoing_time_TDATA),
    .vld_out(regslice_both_outgoing_time_U_vld_out),
    .ack_out(outgoing_time_TREADY),
    .apdone_blk(regslice_both_outgoing_time_U_apdone_blk)
);

simple_threshold_regslice_both #(
    .DataWidth( 96 ))
regslice_both_outgoing_meta_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(outgoing_meta_TDATA_int_regslice),
    .vld_in(outgoing_meta_TVALID_int_regslice),
    .ack_in(outgoing_meta_TREADY_int_regslice),
    .data_out(outgoing_meta_TDATA),
    .vld_out(regslice_both_outgoing_meta_U_vld_out),
    .ack_out(outgoing_meta_TREADY),
    .apdone_blk(regslice_both_outgoing_meta_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp8_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp8_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp8)) begin
                ap_block_pp0_stage2_subdone_grp8_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_predicate_pred100_state7 <= ((icmp_ln60_reg_213 == 1'd1) & (tmp_6_reg_209 == 1'd1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (tmp_reg_185 == 1'd1));
        icmp_ln65_reg_227 <= icmp_ln65_fu_179_p2;
        incoming_meta_read_reg_222 <= incoming_meta_TDATA_int_regslice;
        incoming_time_read_reg_217 <= incoming_time_TDATA_int_regslice;
        tmp_reg_185 <= tmp_nbreadreq_fu_60_p3;
        tmp_reg_185_pp0_iter1_reg <= tmp_reg_185;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001_grp5) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_predicate_pred128_state8 <= ((tmp_6_reg_209 == 1'd1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (icmp_ln65_reg_227 == 1'd1) & (tmp_reg_185_pp0_iter1_reg == 1'd1));
        tmp_1_reg_189 <= tmp_1_nbreadreq_fu_68_p3;
        tmp_1_reg_189_pp0_iter1_reg <= tmp_1_reg_189;
        tmp_2_reg_193 <= tmp_2_nbreadreq_fu_76_p3;
        tmp_2_reg_193_pp0_iter1_reg <= tmp_2_reg_193;
        tmp_3_reg_197 <= tmp_3_nbreadreq_fu_84_p3;
        tmp_3_reg_197_pp0_iter1_reg <= tmp_3_reg_197;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        icmp_ln60_reg_213 <= icmp_ln60_fu_169_p2;
        tmp_6_reg_209 <= outgoing_meta_TREADY_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001_grp8) & (1'b0 == ap_block_pp0_stage2_subdone_grp8_done_reg) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_4_reg_201 <= outgoing_order_TREADY_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        tmp_5_reg_205 <= outgoing_time_TREADY_int_regslice;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

assign ap_reset_idle_pp0 = 1'b0;

always @ (*) begin
    if (((tmp_6_reg_209 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (tmp_reg_185 == 1'd1) & (1'b0 == ap_block_pp0_stage0_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        incoming_meta_TDATA_blk_n = incoming_meta_TVALID_int_regslice;
    end else begin
        incoming_meta_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op51_read_state6 == 1'b1))) begin
        incoming_meta_TREADY_int_regslice = 1'b1;
    end else begin
        incoming_meta_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_6_reg_209 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (tmp_reg_185 == 1'd1) & (1'b0 == ap_block_pp0_stage0_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        incoming_time_TDATA_blk_n = incoming_time_TVALID_int_regslice;
    end else begin
        incoming_time_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op50_read_state6 == 1'b1))) begin
        incoming_time_TREADY_int_regslice = 1'b1;
    end else begin
        incoming_time_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op53_write_state6 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp8_done_reg) & (1'b0 == ap_block_pp0_stage2_grp8) & (ap_predicate_pred128_state8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp5) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_predicate_op62_write_state7 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp5) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_predicate_op58_write_state7 == 1'b1)))) begin
        outgoing_meta_TDATA_blk_n = outgoing_meta_TREADY_int_regslice;
    end else begin
        outgoing_meta_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if ((1'b1 == ap_condition_523)) begin
            outgoing_meta_TDATA_int_regslice = incoming_meta_read_reg_222;
        end else if ((1'b1 == ap_condition_519)) begin
            outgoing_meta_TDATA_int_regslice = incoming_meta_TDATA_int_regslice;
        end else begin
            outgoing_meta_TDATA_int_regslice = 'bx;
        end
    end else begin
        outgoing_meta_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp5) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_predicate_op62_write_state7 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op53_write_state6 == 1'b1)))) begin
        outgoing_meta_TVALID_int_regslice = 1'b1;
    end else begin
        outgoing_meta_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln60_reg_213 == 1'd1) & (tmp_6_reg_209 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (tmp_reg_185 == 1'd1) & (1'b0 == ap_block_pp0_stage0_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln60_fu_169_p2 == 1'd1) & (grp_nbwritereq_fu_108_p3 == 1'd1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (tmp_reg_185 == 1'd1) & (1'b0 == ap_block_pp0_stage4_grp1) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((tmp_6_reg_209 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (tmp_reg_185 == 1'd1) & (1'b0 == ap_block_pp0_stage0_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln65_fu_179_p2 == 1'd1)) | ((tmp_6_reg_209 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_5_reg_205 
    == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (1'b0 == ap_block_pp0_stage1_grp5) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln65_reg_227 == 1'd1) & (tmp_reg_185_pp0_iter1_reg == 1'd1)))) begin
        outgoing_order_TDATA_blk_n = outgoing_order_TREADY_int_regslice;
    end else begin
        outgoing_order_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_01001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op57_write_state6 == 1'b1))) begin
        outgoing_order_TDATA_int_regslice = 64'd72057596101656832;
    end else if (((1'b0 == ap_block_pp0_stage4_01001_grp1) & (1'b1 == 1'b1) & (ap_predicate_op47_write_state5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        outgoing_order_TDATA_int_regslice = 64'd2063728896;
    end else begin
        outgoing_order_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op57_write_state6 == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001_grp1) & (1'b1 == 1'b1) & (ap_predicate_op47_write_state5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        outgoing_order_TVALID_int_regslice = 1'b1;
    end else begin
        outgoing_order_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln60_reg_213 == 1'd1) & (tmp_6_reg_209 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (tmp_reg_185 == 1'd1) & (1'b0 == ap_block_pp0_stage0_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_6_reg_209 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (1'b0 == ap_block_pp0_stage1_grp5) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln65_reg_227 == 1'd1) & (tmp_reg_185_pp0_iter1_reg == 1'd1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp8_done_reg) & (1'b0 == ap_block_pp0_stage2_grp8) & (ap_predicate_pred128_state8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp5) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_predicate_pred100_state7 == 1'b1)))) begin
        outgoing_time_TDATA_blk_n = outgoing_time_TREADY_int_regslice;
    end else begin
        outgoing_time_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if ((1'b1 == ap_condition_530)) begin
            outgoing_time_TDATA_int_regslice = incoming_time_read_reg_217;
        end else if ((1'b1 == ap_condition_526)) begin
            outgoing_time_TDATA_int_regslice = incoming_time_TDATA_int_regslice;
        end else begin
            outgoing_time_TDATA_int_regslice = 'bx;
        end
    end else begin
        outgoing_time_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp5) & (ap_predicate_op63_write_state7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op54_write_state6 == 1'b1)))) begin
        outgoing_time_TVALID_int_regslice = 1'b1;
    end else begin
        outgoing_time_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_6_reg_209 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (tmp_reg_185 == 1'd1) & (1'b0 == ap_block_pp0_stage0_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        top_ask_TDATA_blk_n = top_ask_TVALID_int_regslice;
    end else begin
        top_ask_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op48_read_state6 == 1'b1))) begin
        top_ask_TREADY_int_regslice = 1'b1;
    end else begin
        top_ask_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((grp_nbwritereq_fu_108_p3 == 1'd1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (tmp_reg_185 == 1'd1) & (1'b0 == ap_block_pp0_stage4_grp1) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        top_bid_TDATA_blk_n = top_bid_TVALID_int_regslice;
    end else begin
        top_bid_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001_grp1) & (1'b1 == 1'b1) & (ap_predicate_op43_read_state5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        top_bid_TREADY_int_regslice = 1'b1;
    end else begin
        top_bid_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_reset_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_pp0_stage0_01001_grp2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter1_grp2));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter1_grp2));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter1_grp2));
end

assign ap_block_pp0_stage0_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter1_grp2));
end

always @ (*) begin
    ap_block_pp0_stage1_01001_grp5 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage1_iter1_grp5));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage1_iter1_grp5));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp5 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage1_iter1_grp5));
end

assign ap_block_pp0_stage1_grp5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage1_iter1_grp5));
end

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((regslice_both_outgoing_meta_U_apdone_blk == 1'b1) | (regslice_both_outgoing_time_U_apdone_blk == 1'b1) | (regslice_both_outgoing_order_U_apdone_blk == 1'b1) | ((1'b0 == ap_block_pp0_stage2_subdone_grp8_done_reg) & (1'b1 == ap_block_state8_pp0_stage2_iter1_grp8))));
end

always @ (*) begin
    ap_block_pp0_stage2_11001_grp8 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp8_done_reg) & (1'b1 == ap_block_state8_pp0_stage2_iter1_grp8));
end

assign ap_block_pp0_stage2_grp8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((regslice_both_outgoing_meta_U_apdone_blk == 1'b1) | (regslice_both_outgoing_time_U_apdone_blk == 1'b1) | (regslice_both_outgoing_order_U_apdone_blk == 1'b1) | ((1'b0 == ap_block_pp0_stage2_subdone_grp8_done_reg) & (1'b1 == ap_block_state8_pp0_stage2_iter1_grp8))));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone_grp8 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp8_done_reg) & (1'b1 == ap_block_state8_pp0_stage2_iter1_grp8));
end

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_01001_grp1 = ((1'b1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage4_iter0_grp1));
end

always @ (*) begin
    ap_block_pp0_stage4_11001 = ((1'b1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage4_iter0_grp1));
end

always @ (*) begin
    ap_block_pp0_stage4_11001_grp1 = ((1'b1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage4_iter0_grp1));
end

assign ap_block_pp0_stage4_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_subdone = ((1'b1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage4_iter0_grp1));
end

always @ (*) begin
    ap_block_state5_pp0_stage4_iter0_grp1 = (((outgoing_order_TREADY_int_regslice == 1'b0) & (ap_predicate_op47_write_state5 == 1'b1)) | ((top_bid_TVALID_int_regslice == 1'b0) & (ap_predicate_op43_read_state5 == 1'b1)));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter1_grp2 = (((outgoing_meta_TREADY_int_regslice == 1'b0) & (ap_predicate_op53_write_state6 == 1'b1)) | ((outgoing_time_TREADY_int_regslice == 1'b0) & (ap_predicate_op54_write_state6 == 1'b1)) | ((outgoing_order_TREADY_int_regslice == 1'b0) & (ap_predicate_op57_write_state6 == 1'b1)) | ((outgoing_order_TREADY_int_regslice == 1'b0) & (ap_predicate_op52_write_state6 == 1'b1)) | ((incoming_meta_TVALID_int_regslice == 1'b0) & (ap_predicate_op51_read_state6 == 1'b1)) | ((incoming_time_TVALID_int_regslice == 1'b0) & (ap_predicate_op50_read_state6 == 1'b1)) | ((top_ask_TVALID_int_regslice == 1'b0) & (ap_predicate_op48_read_state6 == 1'b1)));
end

always @ (*) begin
    ap_block_state7_pp0_stage1_iter1_grp5 = (((outgoing_meta_TREADY_int_regslice == 1'b0) & (ap_predicate_op62_write_state7 == 1'b1)) | ((outgoing_meta_TREADY_int_regslice == 1'b0) & (ap_predicate_op58_write_state7 == 1'b1)) | ((outgoing_time_TREADY_int_regslice == 1'b0) & (ap_predicate_op63_write_state7 == 1'b1)) | ((outgoing_time_TREADY_int_regslice == 1'b0) & (ap_predicate_op59_write_state7 == 1'b1)) | ((outgoing_order_TREADY_int_regslice == 1'b0) & (ap_predicate_op61_write_state7 == 1'b1)));
end

always @ (*) begin
    ap_block_state8_pp0_stage2_iter1_grp8 = (((outgoing_meta_TREADY_int_regslice == 1'b0) & (ap_predicate_op65_write_state8 == 1'b1)) | ((outgoing_time_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state8 == 1'b1)));
end

always @ (*) begin
    ap_condition_519 = ((1'b0 == ap_block_pp0_stage0_01001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op53_write_state6 == 1'b1));
end

always @ (*) begin
    ap_condition_523 = ((1'b0 == ap_block_pp0_stage1_01001_grp5) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_predicate_op62_write_state7 == 1'b1));
end

always @ (*) begin
    ap_condition_526 = ((1'b0 == ap_block_pp0_stage0_01001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op54_write_state6 == 1'b1));
end

always @ (*) begin
    ap_condition_530 = ((1'b0 == ap_block_pp0_stage1_01001_grp5) & (ap_predicate_op63_write_state7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op43_read_state5 = ((grp_nbwritereq_fu_108_p3 == 1'd1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (tmp_reg_185 == 1'd1));
end

always @ (*) begin
    ap_predicate_op47_write_state5 = ((icmp_ln60_fu_169_p2 == 1'd1) & (grp_nbwritereq_fu_108_p3 == 1'd1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (tmp_reg_185 == 1'd1));
end

always @ (*) begin
    ap_predicate_op48_read_state6 = ((tmp_6_reg_209 == 1'd1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (tmp_reg_185 == 1'd1));
end

always @ (*) begin
    ap_predicate_op50_read_state6 = ((tmp_6_reg_209 == 1'd1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (tmp_reg_185 == 1'd1));
end

always @ (*) begin
    ap_predicate_op51_read_state6 = ((tmp_6_reg_209 == 1'd1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (tmp_reg_185 == 1'd1));
end

always @ (*) begin
    ap_predicate_op52_write_state6 = ((icmp_ln60_reg_213 == 1'd1) & (tmp_6_reg_209 == 1'd1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (tmp_reg_185 == 1'd1));
end

always @ (*) begin
    ap_predicate_op53_write_state6 = ((icmp_ln60_reg_213 == 1'd1) & (tmp_6_reg_209 == 1'd1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (tmp_reg_185 == 1'd1));
end

always @ (*) begin
    ap_predicate_op54_write_state6 = ((icmp_ln60_reg_213 == 1'd1) & (tmp_6_reg_209 == 1'd1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (tmp_reg_185 == 1'd1));
end

always @ (*) begin
    ap_predicate_op57_write_state6 = ((tmp_6_reg_209 == 1'd1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (tmp_reg_185 == 1'd1) & (icmp_ln65_fu_179_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op58_write_state7 = ((icmp_ln60_reg_213 == 1'd1) & (tmp_6_reg_209 == 1'd1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (tmp_reg_185_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op59_write_state7 = ((icmp_ln60_reg_213 == 1'd1) & (tmp_6_reg_209 == 1'd1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (tmp_reg_185_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op61_write_state7 = ((tmp_6_reg_209 == 1'd1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (icmp_ln65_reg_227 == 1'd1) & (tmp_reg_185_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op62_write_state7 = ((tmp_6_reg_209 == 1'd1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (icmp_ln65_reg_227 == 1'd1) & (tmp_reg_185_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op63_write_state7 = ((tmp_6_reg_209 == 1'd1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197 == 1'd1) & (tmp_2_reg_193 == 1'd1) & (tmp_1_reg_189 == 1'd1) & (icmp_ln65_reg_227 == 1'd1) & (tmp_reg_185_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op65_write_state8 = ((tmp_6_reg_209 == 1'd1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197_pp0_iter1_reg == 1'd1) & (tmp_2_reg_193_pp0_iter1_reg == 1'd1) & (tmp_1_reg_189_pp0_iter1_reg == 1'd1) & (icmp_ln65_reg_227 == 1'd1) & (tmp_reg_185_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op66_write_state8 = ((tmp_6_reg_209 == 1'd1) & (tmp_5_reg_205 == 1'd1) & (tmp_4_reg_201 == 1'd1) & (tmp_3_reg_197_pp0_iter1_reg == 1'd1) & (tmp_2_reg_193_pp0_iter1_reg == 1'd1) & (tmp_1_reg_189_pp0_iter1_reg == 1'd1) & (icmp_ln65_reg_227 == 1'd1) & (tmp_reg_185_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ask_price_fu_175_p1 = top_ask_TDATA_int_regslice[15:0];

assign bid_price_fu_165_p1 = top_bid_TDATA_int_regslice[15:0];

assign grp_nbwritereq_fu_108_p3 = outgoing_meta_TREADY_int_regslice;

assign icmp_ln60_fu_169_p2 = ((bid_price_fu_165_p1 > 16'd7014) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_179_p2 = ((ask_price_fu_175_p1 < 16'd7014) ? 1'b1 : 1'b0);

assign incoming_meta_TREADY = regslice_both_incoming_meta_U_ack_in;

assign incoming_time_TREADY = regslice_both_incoming_time_U_ack_in;

assign outgoing_meta_TVALID = regslice_both_outgoing_meta_U_vld_out;

assign outgoing_order_TVALID = regslice_both_outgoing_order_U_vld_out;

assign outgoing_time_TVALID = regslice_both_outgoing_time_U_vld_out;

assign tmp_1_nbreadreq_fu_68_p3 = top_ask_TVALID_int_regslice;

assign tmp_2_nbreadreq_fu_76_p3 = incoming_time_TVALID_int_regslice;

assign tmp_3_nbreadreq_fu_84_p3 = incoming_meta_TVALID_int_regslice;

assign tmp_nbreadreq_fu_60_p3 = top_bid_TVALID_int_regslice;

assign top_ask_TREADY = regslice_both_top_ask_U_ack_in;

assign top_bid_TREADY = regslice_both_top_bid_U_ack_in;


reg find_kernel_block = 0;
// synthesis translate_off
`include "simple_threshold_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //simple_threshold

